Repository SignalK/signalk-server, pull requests merged in 2022-11, with the labels that each got.

#1494 chore: increase npm fetch timeout
  docker/Dockerfile
Labels: chore

#1493 feature: add Swagger and first OpenApi descriptions for discover and security/authentication APIs
  README.md
  package.json
  packages/server-admin-ui/src/components/Sidebar/Sidebar.js
  src/api/apps/openApi.json
  src/api/apps/openApi.ts
  src/api/discovery/openApi.json
  src/api/discovery/openApi.ts
  src/api/security/openApi.json
  src/api/security/openApi.ts
  src/api/swagger.ts
  src/interfaces/rest.js
  src/serverroutes.ts
  tsconfig.json
Labels: feature

#1495 fix: npm timeout in docker build
  docker/Dockerfile
Labels: chore

#1496 fix: logout response as JSON
  src/tokensecurity.js
Labels: fix

#1478 fix: CORS: security routes and origin handling
  package.json
  packages/server-admin-ui/src/views/security/Settings.js
  public/examples/loginform.html
  src/cors.ts
  src/index.ts
  src/security.ts
  src/serverroutes.ts
Labels: fix

#1455 feature: make Seatalk 1 python3 compatible (pigpio-seatalk.js)
  packages/streams/pigpio-seatalk.js
Labels: feature

#1497 chore: optimise Docker master build
  .github/workflows/build-docker.yml
  docker/Dockerfile
  docker/startup.sh
  src/config/config.ts
Labels: chore
