Repository SignalK/signalk-server, pull requests merged in 2023-07, with the labels that each got.

#1582 Fix: Error message when logging in is shown properly
  packages/server-admin-ui/src/actions.js
Labels: fix

#1580 Fix: Resolve uncaught errors when not logged in
  packages/server-admin-ui/src/actions.js
Labels: fix

#1551 Gpsd client package to node-gpsd-client, add reconnect
  packages/streams/gpsd.js
  packages/streams/package.json
Labels: feature

#1578 Feature: minimum version check
  bin/signalk-server
  package.json
Labels: feature

#1586 feature: override for MFD addresses
  README.md
  src/interfaces/mfd_webapp.ts
Labels: feature

#1589 Update broken link to SeaTalk doc.
  raspberry_pi_installation.md
Labels: doc

#1590 New pictures due to opto input change
  Seatalk(GPIO).md
Labels: doc
