Repository SignalK/signalk-server, pull requests merged in 2023-11, with the labels that each got.

#1650 fix: use selfsigned instead of devcert for certificate generation
  package.json
  src/security.ts
Labels: fix

#1584 chore: run tests with node 16,18 and 20
  .github/workflows/test.yml
Labels: other

#1648 Doc: updated installation of NodeJS, add paths for NMEA sample files + cosmetics
  docs/src/installation/raspberry_pi_installation.md
  docs/src/setup/SK_file_stream_N2K.png
  docs/src/setup/configuration.md
Labels: doc
