Repository SignalK/signalk-server, pull requests merged in 2023-03, with the labels that each got.

#1524 feature: add support for the Actisense W2K-1
  packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js
  packages/streams/simple.js
Labels: feature

#1521 [Fix:] Resource-Provider: process only the files in resource folders.
  packages/resources-provider-plugin/src/lib/filestorage.ts
Labels: fix

#1515 feature: support openApi in plugins
  SERVERPLUGINS.md
  src/api/apps/openApi.ts
  src/api/course/openApi.ts
  src/api/discovery/openApi.ts
  src/api/notifications/openApi.ts
  src/api/resources/openApi.ts
  src/api/security/openApi.ts
  src/api/swagger.ts
  src/index.ts
  src/interfaces/plugins.ts
  src/serverroutes.ts
  test/plugin-test-config/node_modules/testplugin/index.js
  test/plugin-test-config/node_modules/testplugin/openApi.json
Labels: feature

#1536 chore: Update Resources-provider documentation
  packages/resources-provider-plugin/README.md
Labels: doc

#1537 fix: serverapi getXX return values
  packages/server-api/src/index.ts
Labels: fix

#1533 doc: rewrite of the readme
  README.md
  TROUBLESHOOTING.md
Labels: doc
