Repository SignalK/signalk-server, pull requests merged in 2023-04, with the labels that each got.

#1541 feature: add getOpenApi in server api/Plugin
  packages/server-api/src/index.ts
Labels: feature

#1547 fix: Remove unused Course OpenAPI schema definitions.
  src/api/course/index.ts
  src/api/course/openApi.json
  test/course.ts
Labels: fix

#1546 chore: Remove unused Resources OpenAPI schema definitions.
  src/api/resources/openApi.json
Labels: chore

#1545 fix: Align the format of the folder name where server state is stored.
  docker/v2_demo/Dockerfile
  src/api/course/index.ts
  src/serverstate/store.ts
  test/ts-servertestutilities.ts
Labels: fix

#1530 chore: release to ghcr.io registry
  .github/workflows/build-base-image.yml
  .github/workflows/build-docker.yml
  .github/workflows/release.yml
  docker/Dockerfile
  docker/Dockerfile_rel
  docker/README.md
  docker/docker-compose.yml
  packages/server-admin-ui/src/views/ServerConfig/ServerUpdate.js
Labels: chore

#1548 feature: Add Route Point Metadata definition to Resources OpenAPI
  src/api/resources/openApi.json
  test/resources.ts
Labels: feature
