Repository SignalK/signalk-server, pull requests merged in 2023-09, with the labels that each got.

#1603 feature: add write statistics to dashboard
  packages/server-admin-ui/src/views/Dashboard/Dashboard.js
  packages/streams/serialport.js
  packages/streams/simple.js
  packages/streams/tcp.js
  src/app.ts
  src/deltastats.ts
  src/index.ts
Labels: feature

#1604 Fix: Issue when creating resources via plugin interface
  src/api/resources/index.ts
Labels: fix

#1616 Chore: Added test-files to gitignore
  .gitignore
Labels: chore

#1619 fix: server admin ui connection activity links
  packages/server-admin-ui/src/views/Dashboard/Dashboard.js
Labels: fix

#1614 Feature: indicate clearly that a plugin needs configuration
  packages/server-admin-ui/scss/_custom.scss
  packages/server-admin-ui/src/views/Configuration/Configuration.js
Labels: feature

#1620 Fix: change approval button for access request to positive (green)
  packages/server-admin-ui/src/views/security/AccessRequests.js
Labels: fix

#1617 feature: connection activity indicator updates
  SERVERPLUGINS.md
  packages/server-admin-ui/src/views/Dashboard/Dashboard.js
Labels: feature

#1631 chore: convert pipedproviders to TypeScript, drop 2 dependencies
  package.json
  src/pipedproviders.js
  src/pipedproviders.ts
Labels: chore

#1591 feature: Expose a Course API interface to plugins.
  packages/server-api/src/coursetypes.ts
  packages/server-api/src/index.ts
  src/api/course/index.ts
  src/api/index.ts
  src/interfaces/plugins.ts
Labels: feature

#1629 feature: add reportOutputMessages to server plugin API
  packages/server-api/src/index.ts
  src/deltastats.ts
  src/interfaces/plugins.ts
Labels: feature
