Repository SignalK/signalk-server, pull requests merged in 2024-11, with the labels that each got.

#1825 feature: add client side cookie to expose login info
  docs/src/develop/webapps.md
  src/tokensecurity.js
Labels: feature

#1822 feature: redirect to webapp by displayName
  docs/src/develop/webapps.md
  src/serverroutes.ts
Labels: feature

#1827 doc: data logging
  docs/src/SUMMARY.md
  docs/src/features/datalogging/datalogging.md
Labels: doc

#1828 fix: bin/log2sk
  bin/log2sk
Labels: fix

#1750 feature: Add NMEA stream handling to Course API.
  docs/src/develop/rest-api/course_api.md
  packages/server-admin-ui/src/views/ServerConfig/Settings.js
  packages/server-api/src/deltas.ts
  src/api/course/index.ts
  src/api/course/openApi.json
  src/config/config.ts
  src/serverroutes.ts
  test/ts-servertestutilities.ts
Labels: feature

#1832 fix: communication.callsignVhf not set properly in baseDeltas.json
  src/config/config.ts
  src/serverroutes.ts
Labels: fix

#1790 feature: show list of apps being installed in the app store
  packages/server-admin-ui/src/views/appstore/Apps/Apps.js
  packages/server-admin-ui/src/views/appstore/Grid/cell-renderers/ActionCellRenderer.js
  packages/server-admin-ui/src/views/appstore/Grid/cell-renderers/VersionCellRenderer.js
Labels: feature

#1835 chore: switch from node-sass to sass
  packages/server-admin-ui/package.json
Labels: chore
