Repository SignalK/signalk-server, pull requests merged in 2024-10, with the labels that each got.

#1783 Fix: server api types
  packages/server-api/src/deltas.test.ts
  packages/server-api/src/deltas.ts
  packages/server-api/tsconfig.json
Labels: fix

#1804 feature: support async plugin.stop implementation
  docs/src/develop/plugins/server_plugin.md
  src/interfaces/plugins.ts
Labels: feature

#1817 Update mdbook version for multiarch support
  package.json
Labels: chore

#1818 Bump nvmrc to match Docker builds
  .nvmrc
Labels: chore

#1819 Add python-version file
  .python-version
Labels: chore

#1823 doc: add note about landingPage setting
  docs/src/setup/configuration.md
Labels: doc

#1809 update: resources-provider config options
  packages/resources-provider-plugin/CHANGELOG.md
  packages/resources-provider-plugin/README.md
  packages/resources-provider-plugin/package.json
  packages/resources-provider-plugin/src/index.ts
Labels: feature

#1808 update: Resources API OpenAPI definition for charts
  src/api/resources/openApi.json
Labels: feature

#1821 feature: add support for bluez for docker
  docker/Dockerfile_base
  docker/bluez/bluezuser.conf
  docker/startup.sh
Labels: feature

#1799 Update: Provide the ability to view and set the default provider used for resource types.
  docs/src/develop/rest-api/resources_api.md
  src/api/course/index.ts
  src/api/resources/index.ts
  src/api/resources/openApi.json
Labels: feature

#1824 fix: resource-provider server-api dependency
  packages/resources-provider-plugin/package.json
Labels: chore
