Repository SignalK/signalk-server, pull requests merged in 2024-12, with the labels that each got.

#1840 Fix: Course API - Update test for valid destination point value
  src/api/course/index.ts
Labels: fix

#1836 chore: update typescript
  .eslintrc.js
  .github/workflows/test.yml
  package.json
  packages/resources-provider-plugin/.eslintrc.js
  packages/resources-provider-plugin/package.json
  packages/resources-provider-plugin/src/index.ts
  packages/resources-provider-plugin/src/lib/filestorage.ts
  packages/server-api/.eslintrc.js
  packages/server-api/package.json
  src/@types/signalk_signalk-schema.d.ts
  src/api/course/index.ts
  src/api/resources/index.ts
  src/api/swagger.ts
  src/config/config.ts
  src/deltaPriority.ts
  src/index.ts
  src/interfaces/mfd_webapp.ts
  src/interfaces/plugins.ts
  src/modules.ts
  src/pipedproviders.ts
  src/security.ts
  src/serialports.ts
  src/serverroutes.ts
  src/serverstate/store.ts
  src/streambundle.d.ts
  src/types.ts
  test/applicationData.js
  test/ts-servertestutilities.ts
Labels: chore

#1843 Revert "fix: communication.callsignVhf not set properly in baseDeltas.json
  src/config/config.ts
  src/serverroutes.ts
Labels: ignore

#1844 Fix: Clear destination on empty or invalid position received via NMEA
  src/api/course/index.ts
Labels: fix

#1701 Upgrade Signal K release action
  .github/workflows/release.yml
Labels: chore

#1596 feature: V2 Autopilot API
  docs/src/develop/plugins/autopilot_provider_plugins.md
  docs/src/develop/rest-api/autopilot_api.md
  docs/src/develop/rest-api/open_api.md
  docs/src/img/autopilot_provider.dia
  docs/src/img/autopilot_provider.svg
  packages/server-api/.gitignore
  packages/server-api/package.json
  packages/server-api/src/autopilotapi.ts
  packages/server-api/src/index.ts
  src/api/autopilot/index.ts
  src/api/autopilot/openApi.json
  src/api/autopilot/openApi.ts
  src/api/index.ts
  src/api/swagger.ts
  src/interfaces/plugins.ts
Labels: feature

#1852 Feature: Add zoom query parameter to Resources OpenAPI definition
  docs/src/develop/rest-api/resources_api.md
  src/api/resources/openApi.json
Labels: feature

#1853 chore: docker release image versions with full, major and latest tags
  .github/workflows/release.yml
Labels: chore

#1854 chore: ubuntu 24.04 base image for test build purposes
  .github/workflows/build-base-image-test.yml
  docker/Dockerfile_base_test
Labels: chore

#1860 fix: docker build tag variable name corrected
  .github/workflows/release.yml
Labels: chore
