Repository SignalK/signalk-server, pull requests merged in 2024-09, with the labels that each got.

#1789 fix: Seatalk1: Auto-detect gpiochip for Raspberry Pi 5
  packages/streams/gpiod-seatalk.js
Labels: feature

#1781 doc: add documentation for nmea0183 options
  docs/src/setup/configuration.md
Labels: doc

#1793 feature: add supportsPut meta data to paths that have put handlers
  src/interfaces/plugins.ts
Labels: feature

#1797 fix: Resources API - Send delta message when resources are added / deleted via the plugin interface.
  packages/resources-provider-plugin/src/index.ts
  src/api/resources/index.ts
Labels: fix

#1796 doc: Remove reference to non-implented `notify()` function
  docs/src/develop/plugins/server_plugin_api.md
Labels: doc
