Repository SignalK/signalk-server, pull requests merged in 2024-06, with the labels that each got.

#1745 fix: data browser does not allow meta to be edited for paths without any meta
  packages/server-admin-ui/src/views/DataBrowser/DataBrowser.js
Labels: fix

#1753 feature: show accessRequests in Security menu
  packages/server-admin-ui/src/components/Sidebar/Sidebar.js
Labels: feature

#1762 fix: plugin configuration switches in the list not updating
  packages/server-admin-ui/src/views/Configuration/Configuration.js
Labels: fix

#1759 fix: plain res.send calls
  src/api/swagger.ts
  src/interfaces/applicationData.js
  src/interfaces/appstore.js
  src/interfaces/logfiles.js
  src/interfaces/plugins.ts
  src/interfaces/providers.js
  src/serverroutes.ts
  src/tokensecurity.js
  test/httpprovider.js
Labels: fix

#1758 chore: remove unused token generation endpoint
  src/serverroutes.ts
Labels: chore

#1764 fix: logfiles directory traversal and authentication
  src/interfaces/logfiles.js
Labels: fix
