Repository SignalK/signalk-server, pull requests merged in 2024-01, with the labels that each got.

#1662 fix: guard against missing plugin schema
  src/interfaces/plugins.ts
Labels: fix

#1660 fix: use multiplexed file timestamps in deltas
  packages/streams/autodetect.js
Labels: fix

#1661 Fix: multiplexed file detection & semicolon handling
  packages/streams/autodetect.js
Labels: fix

#1657 Event handling improvements: events over WebSocket, endpoint for events routing data, event dispatch error handling
  packages/server-admin-ui/src/views/Webapps/Embedded.js
  packages/streams/canboatjs.js
  src/events.ts
  src/index.ts
  src/interfaces/plugins.ts
  src/interfaces/ws.js
  src/pipedproviders.ts
  src/security.ts
  src/serverroutes.ts
Labels: feature

#1664 Info that this Seatalk setup will not run on a Raspberry Pi 5 !!
  docs/src/setup/seatalk/seatalk.md
Labels: doc
