Repository SignalK/signalk-server, pull requests merged in 2024-03, with the labels that each got.

#1685 Fix: Resources API - Handle requests to GET chart tiles.
  src/api/resources/index.ts
Labels: fix

#1689 baseimage node20 and npmjs settings for docker
  docker/Dockerfile
  docker/Dockerfile_base
  docker/Dockerfile_rel
Labels: chore

#1687 fix: add guard against empty settings file
  src/config/config.ts
Labels: fix

#1691 fix: rememberme cookie expiration
  src/tokensecurity.js
Labels: fix

#1684 Fix: disabled plugins no longer have an active API interface
  src/interfaces/plugins.ts
  test/plugins.js
Labels: fix

#1700 Fix: revert plugin API change that broke plugin configuration saving
  src/interfaces/plugins.ts
  test/plugins.js
Labels: fix

#1696 fix: test baseimage docker after build by building SK release docker image without pushing it to registry
  .github/workflows/build-base-image.yml
Labels: chore

#1694 doc: add applicationData documentation
  docs/src/develop/webapps.md
Labels: doc

#1704 feat: add Kip to automatically installed webapps
  package.json
  src/modules.test.js
Labels: feature
