Repository SignalK/signalk-server, pull requests merged in 2024-02, with the labels that each got.

#1670 feature: rememberme expires to NEVER
  src/tokensecurity.js
Labels: feature

#1672 fix: remove scroll when toggling plugin
  packages/server-admin-ui/src/views/Configuration/Configuration.js
Labels: fix

#1676 upgrade Github Actions
  .github/workflows/build-base-image.yml
  .github/workflows/build-docker.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: chore

#1674 feature: improve Server log & data log files UI
  packages/server-admin-ui/src/components/Sidebar/Sidebar.js
  packages/server-admin-ui/src/views/ServerConfig/Logging.js
  packages/server-admin-ui/src/views/ServerConfig/ServerLog.js
Labels: feature

#1669 SK Server Admin UI Activity View Update
  packages/server-admin-ui/src/views/Dashboard/Dashboard.js
Labels: feature

#1678 fix: support for NEVER in RememberMe expires
  src/tokensecurity.js
Labels: fix
