Repository SignalK/signalk-server, pull requests merged in 2024-04, with the labels that each got.

#1692 doc: add Authentication and Session Management
  docs/src/develop/webapps.md
Labels: doc

#1679 Refactor UI of the Appstore page
  package.json
  packages/server-admin-ui/package.json
  packages/server-admin-ui/scss/core/_grid.scss
  packages/server-admin-ui/scss/style.scss
  packages/server-admin-ui/src/components/Sidebar/Sidebar.js
  packages/server-admin-ui/src/containers/Full/Full.js
  packages/server-admin-ui/src/views/appstore/Apps/Apps.js
  packages/server-admin-ui/src/views/appstore/Apps/AppsList.js
  packages/server-admin-ui/src/views/appstore/Apps/ThisSession.js
  packages/server-admin-ui/src/views/appstore/Apps/WarningBox.js
  packages/server-admin-ui/src/views/appstore/AppsList.js
  packages/server-admin-ui/src/views/appstore/Grid/cell-renderers/ActionCellRenderer.js
  packages/server-admin-ui/src/views/appstore/Grid/cell-renderers/NameCellRenderer.js
  packages/server-admin-ui/src/views/appstore/Grid/cell-renderers/TypeCellRenderer.js
  packages/server-admin-ui/src/views/appstore/appStore.scss
  packages/server-admin-ui/webpack.config.js
  src/categories.ts
Labels: feature

#1710 chore: Resources - update plugin catagory keyword
  packages/resources-provider-plugin/CHANGELOG.md
  packages/resources-provider-plugin/README.md
  packages/resources-provider-plugin/package.json
Labels: chore

#1713 fix: remove api.npms.io
  src/modules.ts
Labels: fix

#1720 fix: reduce ws meta tracking memory consumption
  src/interfaces/ws.js
Labels: fix

#1719 fix: check ws max send buffer size over time
  docs/src/installation/command_line.md
  src/interfaces/ws.js
Labels: fix

#1724 Appstore UI/column version
  packages/server-admin-ui/src/views/appstore/Apps/Apps.js
  packages/server-admin-ui/src/views/appstore/AppsList.js
  packages/server-admin-ui/src/views/appstore/Grid/cell-renderers/ActionCellRenderer.js
  packages/server-admin-ui/src/views/appstore/Grid/cell-renderers/NameCellRenderer.js
  packages/server-admin-ui/src/views/appstore/Grid/cell-renderers/VersionCellRenderer.js
  packages/server-admin-ui/src/views/appstore/appStore.scss
Labels: feature

#1630 feature: Add Feature discovery API endpoint and plugin interface
  docs/src/develop/plugins/server_plugin_api.md
  docs/src/develop/webapps.md
  packages/server-api/src/index.ts
  src/api/discovery/index.ts
  src/api/discovery/openApi.json
  src/api/index.ts
  src/app.ts
  src/index.ts
  src/interfaces/plugins.ts
Labels: feature

#1729 fix: npm run watch not working
  package.json
Labels: fix

#1715 feat: Allow for users without password
  src/security.ts
  src/tokensecurity.js
  test/security.js
  test/servertestutilities.js
Labels: feature
