Repository SignalK/signalk-server, pull requests merged in 2025-07, with the labels that each got.

#2027 fix: lint failing because of previous changes to version.ts
  src/version.ts
Labels: ignore

#2033 Databrowser layout & responsiveness improvements
  packages/server-admin-ui/src/views/DataBrowser/DataBrowser.js
Labels: feature

#2032 chore: remove unused deps
  package.json
Labels: chore

#2026 fix: empty communication map sent when filtering self static data
  src/index.ts
Labels: fix
