Repository SignalK/signalk-server, pull requests merged in 2025-04, with the labels that each got.

#1919 chore: fix Dependabot config
  .github/dependabot.yml
Labels: chore

#1913 feat: Add support for plugins published as ESM modules with ESM dependencies
  .gitignore
  .npmignore
  bin/log2sk
  bin/signalk-server
  bin/signalk-server-setup
  docs/src/develop/plugins/server_plugin.md
  index.js
  package.json
  packages/resources-provider-plugin/package.json
  packages/resources-provider-plugin/tsconfig.json
  packages/server-admin-ui/package.json
  packages/server-api/package.json
  packages/server-api/src/index.ts
  packages/server-api/src/propertyvalues.d.ts
  packages/server-api/src/propertyvalues.test.d.ts
  packages/server-api/src/types.d.ts
  packages/server-api/tsconfig.json
  packages/streams/package.json
  src/config/config.ts
  src/index.ts
  src/interfaces/plugins.ts
  src/modules.ts
  test/acls.js
  test/deltaPriority.ts
  test/deltacache.js
  test/history.js
  test/modules.js
  test/plugin-test-config/node_modules/esm-plugin/index.js
  test/plugin-test-config/node_modules/esm-plugin/package.json
  test/plugins.js
  test/providers.js
  test/put.js
  test/servertestutilities.js
  tsconfig.base.json
  tsconfig.json
  util/start-stop.js
Labels: feature

#1927 chore: fix react-json-tree usage after update
  packages/server-admin-ui/src/views/DataBrowser/DataBrowser.js
Labels: chore

#1936 chore: Remove broken freeport-promise package
  package.json
  src/types/freeport-promise/index.d.ts
  test/applicationData.js
  test/history.js
  test/metadata.js
  test/multiple-values.js
  test/plugins.js
  test/providers.js
  test/put.js
  test/security.js
  test/subscriptions.js
  test/ts-servertestutilities.ts
Labels: chore

#1934 chore: fix docker dev build (typedoc-signalk-theme)
  .github/workflows/build-docker.yml
  .npmignore
Labels: chore

#1929 feature: Update Dockerfile_base_22.04 and Dockerfile_base_24.04 to use Node.js v22
  docker/Dockerfile_base_22.04
  docker/Dockerfile_base_24.04
Labels: feature

#1930 feature: Add support for Node 22, drop Node 18
  .github/workflows/test.yml
  .nvmrc
  README.md
  docs/develop/plugins/README.md
  docs/installation/README.md
  docs/installation/raspberry_pi_installation.md
  docs/installation/updating.md
  package.json
  tsconfig.base.json
Labels: feature

#1935 chore: use semver in place of compare-versions
  package.json
  src/interfaces/appstore.js
Labels: chore

#1918 chore: Add StreamBundle and SubscriptionManager to ServerAPI, improve related types
  docs/develop/plugins/deltas.md
  package.json
  packages/server-api/src/@types/baconjs.d.ts
  packages/server-api/src/deltas.ts
  packages/server-api/src/index.ts
  packages/server-api/src/propertyvalues.ts
  packages/server-api/src/serverapi.ts
  packages/server-api/src/streambundle.ts
  packages/server-api/src/subscriptionmanager.ts
  packages/server-api/src/types.ts
  src/@types/baconjs.d.ts
  src/api/course/index.ts
  src/app.ts
  src/config/config.ts
  src/deltacache.ts
  src/index.ts
  src/interfaces/plugins.ts
  src/interfaces/tcp.ts
  src/serverroutes.ts
  src/streambundle.d.ts
  src/streambundle.js
  src/streambundle.ts
  src/subscriptionmanager.ts
  src/types.ts
  src/zones.ts
Labels: chore

#1942 chore: fix & simplify development docker build
  .github/workflows/build-docker.yml
  docker/Dockerfile
  package.json
  packages/server-api/package.json
Labels: chore

#1943 docker: document local build, refactor & improve build
  .github/workflows/build-docker.yml
  docker/Dockerfile
  docker/README.md
Labels: chore

#1941 fix: copy to clipboard
  packages/server-admin-ui/src/views/DataBrowser/DataBrowser.js
Labels: fix

#1946 chore: extract mocha config to file
  .mocharc.js
  package.json
  packages/server-api/package.json
Labels: chore

#1961 fix: deltaPriority code sets update.values to undefined when there are no values
  src/deltaPriority.ts
  test/deltaPriority.ts
Labels: fix
