Repository SignalK/signalk-server, pull requests merged in 2025-08, with the labels that each got.

#2034 chore: @signalk/typedoc-signalk-theme
  .github/workflows/build-docker.yml
  package.json
  packages/typedoc-theme/package.json
  typedoc.json
Labels: chore

#2067 fix: error when creating new connections
  packages/server-admin-ui/package.json
Labels: fix

#2055 Revert docker pr builds
  .github/workflows/build-docker.yml
Labels: chore

#2080 fix: test run on Node v24
  test/deltaPriority.ts
Labels: fix, chore

#2084 fix: nodejs 24.x for arm64 and amd64 not arm/v7
  .github/workflows/build-base-image.yml
Labels: chore

#2068 fix: sending to YDWG over udp not working
  packages/server-admin-ui/src/views/ServerConfig/BasicProvider.js
  packages/streams/udp.js
Labels: fix

#2086 fix: timestamp and callback in server-api ActionHandler/ActionResult
  packages/server-api/src/serverapi.ts
Labels: fix

#2081 fix: Align chart server type OpenAPI definitions.
  src/api/resources/openApi.json
Labels: fix

#2085 fix: docker build housekeeping to remove all temporary files
  .github/workflows/build-docker.yml
  .github/workflows/release.yml
Labels: chore
