Repository SignalK/signalk-server, pull requests merged in 2025-05, with the labels that each got.

#1959 chore: Remove unused public assets
  public/bootstrap/LICENSE
  public/bootstrap/dist/css/bootstrap-theme.css
  public/bootstrap/dist/css/bootstrap-theme.css.map
  public/bootstrap/dist/css/bootstrap-theme.min.css
  public/bootstrap/dist/css/bootstrap-theme.min.css.map
  public/bootstrap/dist/css/bootstrap.css
  public/bootstrap/dist/css/bootstrap.css.map
  public/bootstrap/dist/css/bootstrap.min.css
  public/bootstrap/dist/css/bootstrap.min.css.map
  public/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
  public/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
  public/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
  public/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
  public/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2
  public/bootstrap/dist/js/bootstrap.js
  public/bootstrap/dist/js/bootstrap.min.js
  public/bootstrap/dist/js/npm.js
  public/jquery/LICENSE.txt
  public/jquery/dist/core.js
  public/jquery/dist/jquery.js
  public/jquery/dist/jquery.min.js
  public/jquery/dist/jquery.min.map
  public/jquery/dist/jquery.slim.js
  public/jquery/dist/jquery.slim.min.js
  public/jquery/dist/jquery.slim.min.map
  public/rapidoc-min.js
  public/rapidoc.html
  public/redoc-try.html
Labels: doc

#1932 Course API: Update course paths when referenced resources are changed.
  packages/server-api/src/coursetypes.ts
  packages/server-api/src/resourcetypes.ts
  src/api/course/index.ts
  src/api/course/openApi.json
  src/api/index.ts
Labels: feature

#1955 chore: Remove node-fetch
  package.json
  packages/resources-provider-plugin/src/lib/filestorage.ts
  packages/server-api/src/resourcetypes.ts
  src/modules.ts
  test/applicationData.js
  test/course.ts
  test/delete.js
  test/history.js
  test/metadata.js
  test/multiple-values.js
  test/plugins.js
  test/providers.js
  test/put.js
  test/resources.ts
  test/security.js
  test/servertestutilities.js
  test/ts-servertestutilities.ts
Labels: dependencies

#1958 feat: enable node source map support
  Procfile
  bin/log2sk
  bin/signalk-generate-token
  bin/signalk-server
  bin/signalk-server-setup
  package.json
  tsconfig.base.json
Labels: feature
