Repository SignalK/signalk-server, pull requests merged in 2025-02, with the labels that each got.

#1871 fix: app store ui not updating to show installing plugins; cache npm response for one minute
  src/modules.ts
Labels: fix

#1868 fix: author in Appstore
  src/modules.ts
Labels: fix

#1876 fix: Kubernetes deployment failure
  README.md
  kubernetes/README.md
  kubernetes/signalk-deployment.yaml
  kubernetes/signalk-ingress.yaml
Labels: fix

#1882 Simplify logic
  src/api/course/index.ts
Labels: ignore

#1883 fix: npm search api window hiding some plugins
  src/modules.ts
Labels: fix

#1878 Fix: Course API - check loaded state href values more rigorously
  src/api/course/index.ts
Labels: fix

#1884 fix: multiplexed playback with empty lines
  packages/streams/autodetect.js
Labels: fix

#1887 chore: docker base images build pipeline upgrade
  .github/workflows/build-base-image-test.yml
  .github/workflows/build-base-image.yml
  docker/Dockerfile_base_22.04
  docker/Dockerfile_base_24.04
Labels: chore

#1888 chore: SK docker images build pipelines upgrades
  .github/workflows/build-docker.yml
  .github/workflows/release.yml
Labels: chore
