Repository SignalK/signalk-server, pull requests merged in 2025-03, with the labels that each got.

#1892 fix: change temp docker images static tag ending to per build
  .github/workflows/build-docker.yml
Labels: chore

#1894 fix: release docker build process fix and improvements
  .github/workflows/release.yml
Labels: chore

#1895 fix: fly.io deployment job order change and tag fix
  .github/workflows/release.yml
Labels: chore

#1898 fix: no meta edit panel for notifications
  packages/server-admin-ui/src/views/DataBrowser/DataBrowser.js
Labels: fix

#1899 Add boolean to delta Value type definition in ServerApi
  packages/server-api/src/deltas.ts
Labels: fix

#1900 doc: Add missing getResource() method in Resources API section.
  docs/src/develop/plugins/server_plugin_api.md
Labels: doc

#1905 fix: Use https for NPM request to avoid redirect
  src/modules.ts
Labels: feature

#1911 chore: remove unused UdpBroadcaster
  src/udpbroadcaster.js
Labels: chore

#1908 chore: fix error when running `npm run build` in development
  packages/server-api/tsconfig.json
Labels: chore

#1902 fix: Make padding consistent in Admin UI
  packages/server-admin-ui/scss/core/_grid.scss
  packages/server-admin-ui/src/views/appstore/Apps/Apps.js
  packages/server-admin-ui/src/views/appstore/appStore.scss
Labels: fix

#1904 doc: how to run the server for development & consolidate contributor docs
  README.md
  docs/src/develop/contributing.md
Labels: doc

#1903 fix(server-admin-ui): Use mark in place of mark+text in minimized sidebar
  README.md
  packages/server-admin-ui/public_src/img/signal-k-logo-image.svg
  packages/server-admin-ui/scss/core/_variables.scss
  src/serverroutes.ts
Labels: feature

#1906 doc: Fix broken link in plugin deprecation warning
  src/interfaces/plugins.ts
Labels: fix

#1912 chore: base Dockerfile updates
  docker/Dockerfile_base_22.04
  docker/Dockerfile_base_24.04
Labels: feature

#1910 chore: remove unused src/dtest.js
  src/dtest.js
Labels: chore
